services:
  amiabot-pages:
    build:
      context: .
      dockerfile: Dockerfile
    image: xiaocaoooo/amiabot-pages:local
    container_name: amiabot-pages
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      SEKAI_ASSET: "snowy,uni,haruki"
      PJSK_PROFILE_BASEURL: ""
      PJSK_PROFILE_HEADERS: '{}'
    restart: unless-stopped
